#!/usr/bin/env bash
#Displays FizzBuzz when the number is a multiple of 3 and 5etc
a=1
while [ $a -le 100 ]
do
if (($a%3==0 && $a%5==0))
then
echo "FizzBuzz"
elif (($a%3==0))
then
echo "Fizz"
elif (($a%5==0))
then 
echo "Buzz"
else
echo "$a"
fi
((a++))
done
