#!/usr/bin/env bash
# This script displays "Best School" 10 times, but displays "Hi" on the 9th iteration
a=1
while [ $a -le 10 ]
do 
if [ $a -eq 9 ]
then
echo "Best School"
echo "Hi"
else
echo "Best School"
fi
((a++))
done
