#!/usr/bin/env bash
#This script displays "bad luck" for the 4th iteration, "good luck" for the 8th iteration, and "Best School" for other iterations
a=1
while [ $a -le 10 ]
do
if [ $a -eq 4 ]
then
echo "bad luck"
elif [ $a -eq 8 ]
then
echo "good luck"
else
echo "Best School"
fi
((a++))
done
