#!/usr/bin/env bash
# File: 11-manage_my_process
# Description: Start, stop, restart manage_my_process
PIDFILE="/var/run/my_process.pid"
SCRIPT="/usr/local/bin/manage_my_process"
case "$1" in
start)
"$SCRIPT" &
echo $! > "$PIDFILE"
echo "manage_my_process started"
;;
stop)
kill $(cat "$PIDFILE" 2>/dev/null) 2>/dev/null
rm -f "$PIDFILE"
echo "manage_my_process started"
;;
restart)
kill $(cat "$PIDFILE" 2>/dev/null) 2>/dev/null
rm -f "$PIDFILE"
"$SCRIPT" &
echo $! > "$PIDFILE"
echo "manage_my_process restarted"
;;
*)
echo "Usage: manage_my_process {start|stop|restart}"
;;
esac
